sudo: required
services:
- docker
script:
- docker build -t $DOCKER_IMAGE .
env:
  global:
  - TAG_PATTERN="^[0-9]+(\.[0-9]+){2}(-(alpha|beta|rc))?$"
  - DOCKER_IMAGE=ffuenf/shopware-php:${TRAVIS_TAG:=$TRAVIS_BUILD_NUMBER}