sudo: required
dist: focal
language: php
php:
- '8.0'
services:
- docker
script:
- docker build -t $DOCKER_IMAGE .
env:
  global:
  - TAG_PATTERN="^[0-9]+(\.[0-9]+){2}(-(alpha|beta|rc))?$"
  - DOCKER_IMAGE=docker-shopware-php:${TRAVIS_TAG:=$TRAVIS_BUILD_NUMBER}
  - secure: q5l1qQkWn7Q6v33fQyICn2rSP7X7jFZpGUwqRLcCEFhAkCUO9I4oiXtq9URBZCGmghfEKtJU9HPmzxxeXwlg/ZKSUj/6zzVUDcPuBgfc828qC/Z8GQZWlTETpZ6np9JJbzqKL39Y6GjyXZoOfAQimP0Vm7q7OgNC+RMqog+g+8/hR6aQcUOvvimrcyyfaHcv49RnycxwWUE6rKLo4QaSFtd7Am2xN6YimeWD+khTwFzBBq+aT2fAKftf8kPb1SU3HdV4pORk+IrlkjRmDHKS75e2CBhRQWg1PsBlS2JxwDbbTi5YU/PjT8t6vvdsgrbtfmuhVBbrltcini97bUhGEFMdob/oGWw9FNe/v204fmkw5z5nakGF48pOLMOdYcANfbbynR/yBwASaeGqhDzLqb6rM2q3fV3BJSQBUg/MAfImk6yBVtjTKfoh/h7b/rA8E6Nkg8VHl5i/licPHf9FD/aA129abv1bq0bAMVjZ9BUrp11usbMHzLQCODlgdjVkBz+Ybe0gaVOAQwygZP4iSEJvWx1S2BHN/agbeTrq4xBB2+Cxk1Q8QtDDAPj5FxUgUv7qy3aJIve+RsNAL3jqW4/hos4xFHEsVsPvNOfX1jeYMMmKtMXpH2ZQRwv/qXvaR5OTktducZL/20zAPWaUr3NgBe/LHYgGbeJwGlXYZgA=
  - secure: e7MuEan/pvHSdwURwnb3QTK74SL8OOY9G6Q3E0yp//F2az8LtBRaadH1s9p+ITCm4PFwysUGH1VOdmSZ7wzEP7XbtSGPoGi9boNVcKNSWVJUrdnCd5cFgc96HDOg29u7PuuoqqNfWK44YQjLyJer614lR4JO0BkYd47cZg2s6+a+UXX6RWxhMWgx6MfbmGCediqYYwtsM0msX+K7IkJLSD1HK8/E8BHzjPNx1epMdTihuPQAh/k7lne1nUvP41GGQzuWnTvI5MXXrDD5qRVUKvTtiUcvOvNYCtW4lntlCztQZTqEimkFlAtOz+m98FM6mhph3QtVrVhWKcB5o6Y72DywpYU2aCrQ2hHIypfehGkl1JkYe+1Ug708x1cAz+6NVDaaOBwUYcHiQq6wJLWGFY/FZhne+Uk/Tcru4wva4Kd3Odp0Ht0nTLam3kugLfFrvb+GZWOd98RWp32XMou5KTVYazMswHcD8ZyGD8H19cfR1n5Mh3TdtRgljEcAtj/WGoKzzV+9hG3wAJTzr3HK9SQLlbdorPhrYcHLJhtCozwtYsJbYc7iDSJq7lJOSl2O7M+yuw2Yo+V5Fw4/bIbkHpOLbw0M6Q5Yg2VfdSx99ETjQedBI+B715U/Yt/R/tHxX5DdGyTpnLSQL1DVayPmm54B6kmd37eBqnmiRDcriH0=
  - secure: Bo9DFbPFdjcYcLWoQEjolj4TwotXMjsxFHJPW44y3qLvQ/R7DVh8cyJxo2SzIgI00ImGYAp2QvHOajV2aPTGmLpbzg0zBpChp6D67kl+hXG/fciASvi6H6CpEPfUY2cRs+p5Fq/ilvT40BDR24lBD4eG/Nx5MeRiHOuFlxaV+uLIWCMkWNXdqDKZv6+OrkoNQ3BLuF5ppxINKnOOhLRy3T0xiF0ufsQcS0lDQl64IoqWFEygOlWjWflxe5ZfnzKZZHcL7PbAJ5G94Zd33JZxWihTQujTGhfRZ0cA68HxmFjSypzFHSJyithpdGzY9j77RS3nWO5Zz2USGbuHCSiAZlF4Kpq0Swq6jsZUucld7dzfbXhTNoh4JaTSVM/Ia8DeB/PVf3NrfEDHNvdmLfZZ2gvry0/TU3f3M0+J6qLx53+vqRIi2ops5qCUO1QeT1eQaomT6005yONTnDwKYhruh1bXxCl3j/Y+o26B2h601cban3EL9sGvkXVNn7M8SyAHCITya0K0mf1RZr4aiZnYoYK+G4VgnpYa1ri/XydKht1ES8JUoSFrblQbJPP4596NCoZGJNHrk2fAJAMoa9zvHlRd+mHFNcDv0tS9fLip1wx5uXvoq2+8VgTRWHKTk+OPqwo+imaNCxj+ft4m3J4PJO6yKmAUjS0iISv3UMYyE3Y=
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-central-1)
- docker build -t docker-shopware-php .
- docker tag $DOCKER_IMAGE public.ecr.aws/u0v0e3b1/$DOCKER_IMAGE
- docker push public.ecr.aws/u0v0e3b1/$DOCKER_IMAGE
